### ISSUE TITLE
convertParameters should handle object type

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/azure-operator#31]
https://github.com/giantswarm/azure-operator/pull/21/files#r141798720

We use `object` type to describe nodes created by ARM templates. `convertParameters` most likely will have to be extended to handle `object` type. I didn't test that yet.

**Comment by Cocotton** [comment]
As seen [here](https://github.com/giantswarm/azure-operator/pull/21#issuecomment-333408557), I manage to deploy a multi-masters cluster without any issues from the `convertParameters` function.

My cluster.yaml looked like this
```
...
  azure:
    keyVault:
      name: "my-cluster-vault"
    masters:
    - vmSize: "Standard_A1"
      dataDiskSizeGB: 50
      adminUsername: "core"
      adminSSHKeyData: "ssh-rsa AAAAB3NzaCMYPUB KEY myUser@myComputer"
      osImage:
        publisher: "CoreOS"
        offer: "CoreOS"
        sku: "Stable"
        version: "1465.7.0"
    - vmSize: "Standard_A2"
      dataDiskSizeGB: 60
      adminUsername: "core"
      adminSSHKeyData: "ssh-rsa AAAAB3NzaCMYPUB KEY myUser@myComputer"
      osImage:
        publisher: "CoreOS"
        offer: "CoreOS"
        sku: "Stable"
        version: "1465.7.0"
    location: "westeurope"
    storage:
      accountType: "Standard_LRS"
    virtualNetwork:
      cidr: "10.0.0.0/16"
      masterSubnetCidr: "10.0.1.0/24"
      workerSubnetCidr: "10.0.2.0/24"
      loadBalancer:
        apiCidr: "10.0.3.0/25"
        etcdCidr: "10.0.3.128/25"
        ingressCidr: "10.0.4.0/25"
```
